# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
 
  config.vm.box = "gusztavvargadr/ubuntu-server-2004-lts"
  config.vm.hostname = "server-abgg"
  config.vm.provider "virtualbox" do |vb|
    vb.name = "ubuntu server"
    vb.memory = 2048
    vb.cpus = 2
  config.vm.synced_folder "./compartida/", "/data", create:true
  end
  
  
end



