# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure("2") do |config|
  config.vm.define "win2019" do |w19|
    w19.vm.box = "StefanScherer/windows_2019"
    w19.vm.provider "virtualbox" do |vb|
      vb.memory=4192
      vb.cpus=4
    end
  w19.vm.network "private.network", ip:"172.19.0.2"  
  end

  config.vm.define "win10" do |w10|
    w10.vm.box = "scotch/box "
    w10.vm.provider "virtualbox" do |vb|
      vb.memory=4192
      vb.cpus=4
    end
  w19.vm.network "private.network", ip:"172.19.0.3"  
  end
end
